In [ ]:
# default_exp data

# fullstream.data

> Data-grabbing module for convenience purposes.

In [ ]:
#export
import jax

In [ ]:
#export
def get_three_blobs(keys=[1, 2, 3],num_points=5000):
    k1, k2, k3 = keys
    sig = jax.random.multivariate_normal(
        jax.random.PRNGKey(k1),
        jax.numpy.asarray([2, 5]),
        jax.numpy.asarray([[1, 0.0], [0.0, 1]]),
        shape=(1, num_points),
    )[0]
    bkg1 = jax.random.multivariate_normal(
        jax.random.PRNGKey(k2),
        jax.numpy.asarray([4, 6]),
        jax.numpy.asarray([[1, 0.6], [0.6, 1]]),
        shape=(1, num_points),
    )[0]
    bkg2 = jax.random.multivariate_normal(
        jax.random.PRNGKey(k3),
        jax.numpy.asarray([5.5, 4.5]),
        jax.numpy.asarray([[1.7, 0.2], [0.2, 1]]),
        shape=(1, num_points),
    )[0]
    return sig, bkg1, bkg2

In [ ]:
get_three_blobs(num_points=10)

/home/phinate/envs/fullstream/lib/python3.7/site-packages/jax-0.1.58-py3.7.egg/jax/lib/xla_bridge.py:119: UserWarning: No GPU/TPU found, falling back to CPU.


(DeviceArray([[1.0140822 , 3.9933395 ],
              [1.7786291 , 3.6547594 ],
              [2.7427552 , 2.859375  ],
              [1.3404367 , 4.933917  ],
              [1.7891407 , 4.6465187 ],
              [0.58730876, 3.0566201 ],
              [3.6297982 , 5.240932  ],
              [0.23836362, 4.2867765 ],
              [2.8603325 , 4.808022  ],
              [2.5360398 , 4.480732  ]], dtype=float32),
 DeviceArray([[5.028805 , 7.892764 ],
              [0.8853359, 4.4692073],
              [4.030621 , 5.4007072],
              [3.758674 , 5.3837028],
              [2.008297 , 5.524648 ],
              [3.2231266, 5.1466904],
              [3.0465481, 4.915827 ],
              [3.473128 , 6.3745284],
              [5.696807 , 7.8797874],
              [4.785487 , 7.1458354]], dtype=float32),
 DeviceArray([[5.321168 , 5.0487185],
              [7.947883 , 3.911863 ],
              [7.0904856, 4.478323 ],
              [5.2363334, 3.685265 ],
              [6.5015497, 5.818321